# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 14:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_task_timestamps'),
        ('solutions', '0002_remove_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='scoped_id',
            field=models.PositiveIntegerField(null=True, editable=False, help_text='Solution id unique for task and author'),
            preserve_default=False,
        ),
    ]
