# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-10 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import inloop.solutions.models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0005_scoped_id_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='archive',
            field=models.FileField(blank=True, upload_to=inloop.solutions.models.get_upload_path),
        ),
    ]
