# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-04 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import inloop.solutions.models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0005_scoped_id_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='archive',
            field=models.FileField(blank=True, null=True, upload_to=inloop.solutions.models.get_archive_upload_path),
        ),
    ]
