# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-02 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0006_solution_archive'),
        ('solutions', '0006_checkpoint_checkpointfile'),
    ]

    operations = [
    ]
