from django.conf.urls import patterns, url

from inloop.tasks import views

urlpatterns = patterns(
    '',
    url(
        r'^$',
        views.index,
        name='index'
    ),
    url(
        r'^new_exercise/$',
        views.submit_new_exercise,
        name='new_exercise'
    ),
    url(
        r'^category/admin/new_category/$',
        views.new_category,
        name='new_category'
    ),
    url(
        r'^category/admin/(?P<short_id>[-\w]+)/edit_category/$',
        views.edit_category,
        name='edit_category'
    ),
    url(
        r'^category/admin/(?P<short_id>[-\w]+)/delete/$',
        views.delete_category,
        name='delete_category'
    ),
    url(
        r'^category/admin/manage/$',
        views.manage_categories,
        name='man_cat'
    ),
    url(
        r'^category/(?P<short_id>[-\w]+)/$',
        views.category,
        name='category'
    ),
    url(
        r'^(?P<slug>[-\w]+)/$',
        views.detail,
        name='detail'
    ),
    url(
        r'^(?P<slug>[-\w]+)/edit/$',
        views.edit,
        name='edit'
    ),
    url(
        r'^(?P<slug>[-\w]+)/results/$',
        views.results,
        name='results'
    ),
    url(
        r'^(?P<slug>[-\w]+)/delete/$',
        views.delete,
        name='delete'
    ),
    url(
        r'^(?P<slug>[-\w]+)/download_solution/(?P<solution_id>[\d]+)/$',
        views.get_solution_as_zip,
        name='solution_as_zip'
    ),
)
