"""
Print out Python code suitable to be used as local_conf.py
"""
import socket
import sys
from os import path
from pprint import pformat
from random import SystemRandom
from string import ascii_letters, digits, punctuation
from time import asctime

RAND = SystemRandom()
CHARS = ascii_letters + digits + punctuation


if not path.exists(".git"):
    sys.exit("You *must* execute this script in the project root.")


def pwgen(length, chars=CHARS):
    return "".join([RAND.choice(chars) for _ in range(length)])


def p(name, value):
    print("{name} = {value}".format(name=name, value=pformat(value)))


# please keep this list sorted, thx.
print("# generated by %s on %s" % (sys.argv[0], asctime()))
p("admins", ())
p("github_secret", pwgen(64))
p("inloop_adm", "inloop")
p("inloop_bin", path.expanduser("~/virtualenv/bin"))
p("inloop_root", path.abspath("."))
p("inloop_run", "inloop-run")
p("media_root", path.expanduser("~inloop-run/media"))
p("pg_host", "127.0.0.1")
p("pg_name", "inloop")
p("pg_pass", pwgen(20, chars=(ascii_letters + digits)))
p("pg_port", 5432)
p("pg_user", "inloop")
p("secret_key", pwgen(64))
p("server_name", socket.getfqdn())
p("server_root", path.expanduser("~/htdocs"))
p("static_root", path.expanduser("~/htdocs/static"))
p("tasks_branch", "master")
p("tasks_repository", "git@github.com:st-tu-dresden/inloop-tasks.git")
