# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-24 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solutions', '0005_scoped_id_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedPlagiarism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veto', models.BooleanField(default=False, help_text='Cancel this detection')),
                ('solution', models.ForeignKey(help_text='The solution that was found to be a rip-off', on_delete=django.db.models.deletion.CASCADE, to='solutions.Solution')),
            ],
        ),
        migrations.CreateModel(
            name='PlagiarismTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('command', models.TextField(default='', help_text='Command that was used to perform the test')),
            ],
        ),
        migrations.AddField(
            model_name='detectedplagiarism',
            name='test',
            field=models.ForeignKey(help_text='The test during which this plagiarism was detected', on_delete=django.db.models.deletion.CASCADE, to='grading.PlagiarismTest'),
        ),
    ]
