# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-24 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import inloop.grading.models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plagiarismtest',
            name='zip_file',
            field=models.FileField(null=True, upload_to=inloop.grading.models.zipfile_upload_path),
        ),
    ]
