# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('output', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stdout', models.TextField(default='')),
                ('stderr', models.TextField(default='')),
                ('return_code', models.SmallIntegerField(default=-1)),
                ('time_taken', models.FloatField(default=0.0)),
                ('passed', models.BooleanField(default=False)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solutions.Solution')),
            ],
        ),
        migrations.AddField(
            model_name='testoutput',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testrunner.TestResult'),
        ),
    ]
