# Generated by Django 2.2.16 on 2020-09-25 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testrunner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='passed',
        ),
    ]
