# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL name', unique=True)),
                ('name', models.CharField(help_text='Category name', max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Task categories',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Task title', max_length=100)),
                ('system_name', models.CharField(help_text='Internally used name', max_length=100)),
                ('slug', models.SlugField(help_text='URL name', unique=True)),
                ('description', models.TextField(help_text='Task description')),
                ('pubdate', models.DateTimeField(help_text='When should the task be published?')),
                ('deadline', models.DateTimeField(blank=True, help_text='Optional date the task is due to', null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Category')),
            ],
        ),
    ]
