# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-28 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_category_order_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['deadline', 'pubdate', 'title']},
        ),
    ]
