# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-12 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20190728_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['title']},
        ),
    ]
