# Generated by Django 2.2.15 on 2020-08-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_default_ordering_by_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='max_submissions',
            field=models.IntegerField(blank=True, help_text='Submission limit (per user, -1 means unlimited, null means default)', null=True),
        ),
    ]
