# Generated by Django 2.2.15 on 2020-09-02 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('tasks', '0008_filetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Make the task only available to the chosen group, or all users if unset', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group'),
        ),
    ]
