name: CI

on:
  push:
  schedule:
  # run checks on main every monday at 05:45
  - cron: '45 5 * * 1'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9']
    env:
      VIRTUALENV_NO_DOWNLOAD: "true"
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: |
          tools/ci-requirements.txt
          poetry.lock
    - name: Setup build tools
      run: |
        pip install -r tools/ci-requirements.txt
        poetry config experimental.new-installer false
    - name: Run tests
      run: nox --force-color --session tests-${{ matrix.python-version }}
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    env:
      VIRTUALENV_NO_DOWNLOAD: "true"
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: |
          tools/ci-requirements.txt
          poetry.lock
    - name: Setup build tools
      run: |
        pip install -r tools/ci-requirements.txt
        poetry config experimental.new-installer false
    - name: Lint
      run: nox --force-color --session lint
